# Optymalizacja pamięci dla runnerów CI i kompilacji lokalnej
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX i Jetpack Compose
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official